/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoJsonPolygonGeometry1 } from './GeoJsonPolygonGeometry1';
import {
    GeoJsonPolygonGeometry1FromJSON,
    GeoJsonPolygonGeometry1FromJSONTyped,
    GeoJsonPolygonGeometry1ToJSON,
    GeoJsonPolygonGeometry1ToJSONTyped,
} from './GeoJsonPolygonGeometry1';

/**
 * 
 * @export
 * @interface AisLiveApiApiLiveAisModelsLiveAisFilterInput
 */
export interface AisLiveApiApiLiveAisModelsLiveAisFilterInput {
    /**
     * 
     * @type {GeoJsonPolygonGeometry1}
     * @memberof AisLiveApiApiLiveAisModelsLiveAisFilterInput
     */
    geometry?: GeoJsonPolygonGeometry1 | null;
    /**
     * 
     * @type {Date}
     * @memberof AisLiveApiApiLiveAisModelsLiveAisFilterInput
     */
    since?: Date | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof AisLiveApiApiLiveAisModelsLiveAisFilterInput
     */
    mmsi?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof AisLiveApiApiLiveAisModelsLiveAisFilterInput
     */
    shipTypes?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AisLiveApiApiLiveAisModelsLiveAisFilterInput
     */
    countryCodes?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof AisLiveApiApiLiveAisModelsLiveAisFilterInput
     */
    includePosition?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AisLiveApiApiLiveAisModelsLiveAisFilterInput
     */
    includeStatic?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AisLiveApiApiLiveAisModelsLiveAisFilterInput
     */
    includeAton?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AisLiveApiApiLiveAisModelsLiveAisFilterInput
     */
    includeSafetyRelated?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AisLiveApiApiLiveAisModelsLiveAisFilterInput
     */
    includeBinaryBroadcastMetHyd?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AisLiveApiApiLiveAisModelsLiveAisFilterInput
     */
    downsample?: boolean;
}

/**
 * Check if a given object implements the AisLiveApiApiLiveAisModelsLiveAisFilterInput interface.
 */
export function instanceOfAisLiveApiApiLiveAisModelsLiveAisFilterInput(value: object): value is AisLiveApiApiLiveAisModelsLiveAisFilterInput {
    return true;
}

export function AisLiveApiApiLiveAisModelsLiveAisFilterInputFromJSON(json: any): AisLiveApiApiLiveAisModelsLiveAisFilterInput {
    return AisLiveApiApiLiveAisModelsLiveAisFilterInputFromJSONTyped(json, false);
}

export function AisLiveApiApiLiveAisModelsLiveAisFilterInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AisLiveApiApiLiveAisModelsLiveAisFilterInput {
    if (json == null) {
        return json;
    }
    return {
        
        'geometry': json['geometry'] == null ? undefined : GeoJsonPolygonGeometry1FromJSON(json['geometry']),
        'since': json['since'] == null ? undefined : (new Date(json['since'])),
        'mmsi': json['mmsi'] == null ? undefined : json['mmsi'],
        'shipTypes': json['shipTypes'] == null ? undefined : json['shipTypes'],
        'countryCodes': json['countryCodes'] == null ? undefined : json['countryCodes'],
        'includePosition': json['includePosition'] == null ? undefined : json['includePosition'],
        'includeStatic': json['includeStatic'] == null ? undefined : json['includeStatic'],
        'includeAton': json['includeAton'] == null ? undefined : json['includeAton'],
        'includeSafetyRelated': json['includeSafetyRelated'] == null ? undefined : json['includeSafetyRelated'],
        'includeBinaryBroadcastMetHyd': json['includeBinaryBroadcastMetHyd'] == null ? undefined : json['includeBinaryBroadcastMetHyd'],
        'downsample': json['downsample'] == null ? undefined : json['downsample'],
    };
}

export function AisLiveApiApiLiveAisModelsLiveAisFilterInputToJSON(json: any): AisLiveApiApiLiveAisModelsLiveAisFilterInput {
    return AisLiveApiApiLiveAisModelsLiveAisFilterInputToJSONTyped(json, false);
}

export function AisLiveApiApiLiveAisModelsLiveAisFilterInputToJSONTyped(value?: AisLiveApiApiLiveAisModelsLiveAisFilterInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geometry': GeoJsonPolygonGeometry1ToJSON(value['geometry']),
        'since': value['since'] == null ? value['since'] : value['since'].toISOString(),
        'mmsi': value['mmsi'],
        'shipTypes': value['shipTypes'],
        'countryCodes': value['countryCodes'],
        'includePosition': value['includePosition'],
        'includeStatic': value['includeStatic'],
        'includeAton': value['includeAton'],
        'includeSafetyRelated': value['includeSafetyRelated'],
        'includeBinaryBroadcastMetHyd': value['includeBinaryBroadcastMetHyd'],
        'downsample': value['downsample'],
    };
}

