/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AisLiveApiApiLatestAisModelsModelFormat = {
    Json: 'Json',
    Geojson: 'Geojson',
    FeatureCollection: 'FeatureCollection'
} as const;
export type AisLiveApiApiLatestAisModelsModelFormat = typeof AisLiveApiApiLatestAisModelsModelFormat[keyof typeof AisLiveApiApiLatestAisModelsModelFormat];


export function instanceOfAisLiveApiApiLatestAisModelsModelFormat(value: any): boolean {
    for (const key in AisLiveApiApiLatestAisModelsModelFormat) {
        if (Object.prototype.hasOwnProperty.call(AisLiveApiApiLatestAisModelsModelFormat, key)) {
            if (AisLiveApiApiLatestAisModelsModelFormat[key as keyof typeof AisLiveApiApiLatestAisModelsModelFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AisLiveApiApiLatestAisModelsModelFormatFromJSON(json: any): AisLiveApiApiLatestAisModelsModelFormat {
    return AisLiveApiApiLatestAisModelsModelFormatFromJSONTyped(json, false);
}

export function AisLiveApiApiLatestAisModelsModelFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): AisLiveApiApiLatestAisModelsModelFormat {
    return json as AisLiveApiApiLatestAisModelsModelFormat;
}

export function AisLiveApiApiLatestAisModelsModelFormatToJSON(value?: AisLiveApiApiLatestAisModelsModelFormat | null): any {
    return value as any;
}

export function AisLiveApiApiLatestAisModelsModelFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): AisLiveApiApiLatestAisModelsModelFormat {
    return value as AisLiveApiApiLatestAisModelsModelFormat;
}

