/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoJsonPolygonGeometry1 } from './GeoJsonPolygonGeometry1';
import {
    GeoJsonPolygonGeometry1FromJSON,
    GeoJsonPolygonGeometry1FromJSONTyped,
    GeoJsonPolygonGeometry1ToJSON,
    GeoJsonPolygonGeometry1ToJSONTyped,
} from './GeoJsonPolygonGeometry1';

/**
 * 
 * @export
 * @interface AisLiveApiApiLatestAisModelsLatestAisFilterInput
 */
export interface AisLiveApiApiLatestAisModelsLatestAisFilterInput {
    /**
     * 
     * @type {GeoJsonPolygonGeometry1}
     * @memberof AisLiveApiApiLatestAisModelsLatestAisFilterInput
     */
    geometry?: GeoJsonPolygonGeometry1 | null;
    /**
     * 
     * @type {Date}
     * @memberof AisLiveApiApiLatestAisModelsLatestAisFilterInput
     */
    since?: Date | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof AisLiveApiApiLatestAisModelsLatestAisFilterInput
     */
    mmsi?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof AisLiveApiApiLatestAisModelsLatestAisFilterInput
     */
    shipTypes?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AisLiveApiApiLatestAisModelsLatestAisFilterInput
     */
    countryCodes?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof AisLiveApiApiLatestAisModelsLatestAisFilterInput
     */
    includePosition?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AisLiveApiApiLatestAisModelsLatestAisFilterInput
     */
    includeStatic?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AisLiveApiApiLatestAisModelsLatestAisFilterInput
     */
    includeAton?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AisLiveApiApiLatestAisModelsLatestAisFilterInput
     */
    includeSafetyRelated?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AisLiveApiApiLatestAisModelsLatestAisFilterInput
     */
    includeBinaryBroadcastMetHyd?: boolean;
}

/**
 * Check if a given object implements the AisLiveApiApiLatestAisModelsLatestAisFilterInput interface.
 */
export function instanceOfAisLiveApiApiLatestAisModelsLatestAisFilterInput(value: object): value is AisLiveApiApiLatestAisModelsLatestAisFilterInput {
    return true;
}

export function AisLiveApiApiLatestAisModelsLatestAisFilterInputFromJSON(json: any): AisLiveApiApiLatestAisModelsLatestAisFilterInput {
    return AisLiveApiApiLatestAisModelsLatestAisFilterInputFromJSONTyped(json, false);
}

export function AisLiveApiApiLatestAisModelsLatestAisFilterInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AisLiveApiApiLatestAisModelsLatestAisFilterInput {
    if (json == null) {
        return json;
    }
    return {
        
        'geometry': json['geometry'] == null ? undefined : GeoJsonPolygonGeometry1FromJSON(json['geometry']),
        'since': json['since'] == null ? undefined : (new Date(json['since'])),
        'mmsi': json['mmsi'] == null ? undefined : json['mmsi'],
        'shipTypes': json['shipTypes'] == null ? undefined : json['shipTypes'],
        'countryCodes': json['countryCodes'] == null ? undefined : json['countryCodes'],
        'includePosition': json['includePosition'] == null ? undefined : json['includePosition'],
        'includeStatic': json['includeStatic'] == null ? undefined : json['includeStatic'],
        'includeAton': json['includeAton'] == null ? undefined : json['includeAton'],
        'includeSafetyRelated': json['includeSafetyRelated'] == null ? undefined : json['includeSafetyRelated'],
        'includeBinaryBroadcastMetHyd': json['includeBinaryBroadcastMetHyd'] == null ? undefined : json['includeBinaryBroadcastMetHyd'],
    };
}

export function AisLiveApiApiLatestAisModelsLatestAisFilterInputToJSON(json: any): AisLiveApiApiLatestAisModelsLatestAisFilterInput {
    return AisLiveApiApiLatestAisModelsLatestAisFilterInputToJSONTyped(json, false);
}

export function AisLiveApiApiLatestAisModelsLatestAisFilterInputToJSONTyped(value?: AisLiveApiApiLatestAisModelsLatestAisFilterInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geometry': GeoJsonPolygonGeometry1ToJSON(value['geometry']),
        'since': value['since'] == null ? value['since'] : value['since'].toISOString(),
        'mmsi': value['mmsi'],
        'shipTypes': value['shipTypes'],
        'countryCodes': value['countryCodes'],
        'includePosition': value['includePosition'],
        'includeStatic': value['includeStatic'],
        'includeAton': value['includeAton'],
        'includeSafetyRelated': value['includeSafetyRelated'],
        'includeBinaryBroadcastMetHyd': value['includeBinaryBroadcastMetHyd'],
    };
}

