/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage
 */
export interface AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage {
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage
     */
    readonly type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage
     */
    messageType?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage
     */
    mmsi?: number;
    /**
     * 
     * @type {Date}
     * @memberof AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage
     */
    msgtime?: Date;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage
     */
    sequenceNumber?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage
     */
    destinationMmsi?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage
     */
    safetyRelatedText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage
     */
    stream?: string | null;
}

/**
 * Check if a given object implements the AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage interface.
 */
export function instanceOfAisSharedMessagesOutputMessagesOutputSafetyRelatedMessage(value: object): value is AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage {
    return true;
}

export function AisSharedMessagesOutputMessagesOutputSafetyRelatedMessageFromJSON(json: any): AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage {
    return AisSharedMessagesOutputMessagesOutputSafetyRelatedMessageFromJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesOutputSafetyRelatedMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'messageType': json['messageType'] == null ? undefined : json['messageType'],
        'mmsi': json['mmsi'] == null ? undefined : json['mmsi'],
        'msgtime': json['msgtime'] == null ? undefined : (new Date(json['msgtime'])),
        'sequenceNumber': json['sequenceNumber'] == null ? undefined : json['sequenceNumber'],
        'destinationMmsi': json['destinationMmsi'] == null ? undefined : json['destinationMmsi'],
        'safetyRelatedText': json['safetyRelatedText'] == null ? undefined : json['safetyRelatedText'],
        'stream': json['stream'] == null ? undefined : json['stream'],
    };
}

export function AisSharedMessagesOutputMessagesOutputSafetyRelatedMessageToJSON(json: any): AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage {
    return AisSharedMessagesOutputMessagesOutputSafetyRelatedMessageToJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesOutputSafetyRelatedMessageToJSONTyped(value?: Omit<AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage, 'type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageType': value['messageType'],
        'mmsi': value['mmsi'],
        'msgtime': value['msgtime'] == null ? value['msgtime'] : value['msgtime'].toISOString(),
        'sequenceNumber': value['sequenceNumber'],
        'destinationMmsi': value['destinationMmsi'],
        'safetyRelatedText': value['safetyRelatedText'],
        'stream': value['stream'],
    };
}

