/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AisSharedMessagesEnumsMetHydBeaufortScale = {
    Flat: 'Flat',
    RipplesWithoutCrests: 'RipplesWithoutCrests',
    SmallWavelets: 'SmallWavelets',
    LargeWavelets: 'LargeWavelets',
    SmallWaves: 'SmallWaves',
    ModerateLongerWaves: 'ModerateLongerWaves',
    LargeWaves: 'LargeWaves',
    SeaHeapsUp: 'SeaHeapsUp',
    ModeratelyHighWaves: 'ModeratelyHighWaves',
    HighWaves: 'HighWaves',
    VeryHighWaves: 'VeryHighWaves',
    ExceptionallyHighWaves: 'ExceptionallyHighWaves',
    HugeWaves: 'HugeWaves',
    DefaultNotAvailable: 'DefaultNotAvailable',
    ReservedForFuture1: 'ReservedForFuture1',
    ReservedForFuture2: 'ReservedForFuture2'
} as const;
export type AisSharedMessagesEnumsMetHydBeaufortScale = typeof AisSharedMessagesEnumsMetHydBeaufortScale[keyof typeof AisSharedMessagesEnumsMetHydBeaufortScale];


export function instanceOfAisSharedMessagesEnumsMetHydBeaufortScale(value: any): boolean {
    for (const key in AisSharedMessagesEnumsMetHydBeaufortScale) {
        if (Object.prototype.hasOwnProperty.call(AisSharedMessagesEnumsMetHydBeaufortScale, key)) {
            if (AisSharedMessagesEnumsMetHydBeaufortScale[key as keyof typeof AisSharedMessagesEnumsMetHydBeaufortScale] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AisSharedMessagesEnumsMetHydBeaufortScaleFromJSON(json: any): AisSharedMessagesEnumsMetHydBeaufortScale {
    return AisSharedMessagesEnumsMetHydBeaufortScaleFromJSONTyped(json, false);
}

export function AisSharedMessagesEnumsMetHydBeaufortScaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AisSharedMessagesEnumsMetHydBeaufortScale {
    return json as AisSharedMessagesEnumsMetHydBeaufortScale;
}

export function AisSharedMessagesEnumsMetHydBeaufortScaleToJSON(value?: AisSharedMessagesEnumsMetHydBeaufortScale | null): any {
    return value as any;
}

export function AisSharedMessagesEnumsMetHydBeaufortScaleToJSONTyped(value: any, ignoreDiscriminator: boolean): AisSharedMessagesEnumsMetHydBeaufortScale {
    return value as AisSharedMessagesEnumsMetHydBeaufortScale;
}

