/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AisSharedMessagesEnumsMetHydIce } from './AisSharedMessagesEnumsMetHydIce';
import {
    AisSharedMessagesEnumsMetHydIceFromJSON,
    AisSharedMessagesEnumsMetHydIceFromJSONTyped,
    AisSharedMessagesEnumsMetHydIceToJSON,
    AisSharedMessagesEnumsMetHydIceToJSONTyped,
} from './AisSharedMessagesEnumsMetHydIce';
import type { AisSharedMessagesEnumsMetHydPrecipitation } from './AisSharedMessagesEnumsMetHydPrecipitation';
import {
    AisSharedMessagesEnumsMetHydPrecipitationFromJSON,
    AisSharedMessagesEnumsMetHydPrecipitationFromJSONTyped,
    AisSharedMessagesEnumsMetHydPrecipitationToJSON,
    AisSharedMessagesEnumsMetHydPrecipitationToJSONTyped,
} from './AisSharedMessagesEnumsMetHydPrecipitation';
import type { AisSharedMessagesEnumsMetHydBeaufortScale } from './AisSharedMessagesEnumsMetHydBeaufortScale';
import {
    AisSharedMessagesEnumsMetHydBeaufortScaleFromJSON,
    AisSharedMessagesEnumsMetHydBeaufortScaleFromJSONTyped,
    AisSharedMessagesEnumsMetHydBeaufortScaleToJSON,
    AisSharedMessagesEnumsMetHydBeaufortScaleToJSONTyped,
} from './AisSharedMessagesEnumsMetHydBeaufortScale';
import type { AisSharedMessagesEnumsMetHydTrend } from './AisSharedMessagesEnumsMetHydTrend';
import {
    AisSharedMessagesEnumsMetHydTrendFromJSON,
    AisSharedMessagesEnumsMetHydTrendFromJSONTyped,
    AisSharedMessagesEnumsMetHydTrendToJSON,
    AisSharedMessagesEnumsMetHydTrendToJSONTyped,
} from './AisSharedMessagesEnumsMetHydTrend';

/**
 * 
 * @export
 * @interface AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
 */
export interface AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd {
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    readonly type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    messageType?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    mmsi?: number;
    /**
     * 
     * @type {Date}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    msgtime?: Date;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    functionalId?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    designatedAreaCode?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    longitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    day?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    hour?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    minute?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    avgWindSpeed?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    windGust?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    windDirection?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    windGustDirection?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    airTemperature?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    relativeHumidity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    dewPoint?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    airPressure?: number | null;
    /**
     * 
     * @type {AisSharedMessagesEnumsMetHydTrend}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    airPressureTendency?: AisSharedMessagesEnumsMetHydTrend;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    horizontalVisibility?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    waterLevel?: number | null;
    /**
     * 
     * @type {AisSharedMessagesEnumsMetHydTrend}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    waterLevelTrend?: AisSharedMessagesEnumsMetHydTrend;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    surfaceCurrentSpeed?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    surfaceCurrentDirection?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    currentSpeed2?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    currentDirection2?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    currentMeasuringLevel2?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    currentSpeed3?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    currentDirection3?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    currentMeasuringLevel3?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    significantWaveHeight?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    wavePeriod?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    waveDirection?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    swellHeight?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    swellPeriod?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    swellDirection?: number | null;
    /**
     * 
     * @type {AisSharedMessagesEnumsMetHydBeaufortScale}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    seaState?: AisSharedMessagesEnumsMetHydBeaufortScale;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    waterTemperature?: number | null;
    /**
     * 
     * @type {AisSharedMessagesEnumsMetHydPrecipitation}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    precipitationType?: AisSharedMessagesEnumsMetHydPrecipitation;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    salinity?: number | null;
    /**
     * 
     * @type {AisSharedMessagesEnumsMetHydIce}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    ice?: AisSharedMessagesEnumsMetHydIce;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd
     */
    stream?: string | null;
}



/**
 * Check if a given object implements the AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd interface.
 */
export function instanceOfAisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd(value: object): value is AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd {
    return true;
}

export function AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHydFromJSON(json: any): AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd {
    return AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHydFromJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHydFromJSONTyped(json: any, ignoreDiscriminator: boolean): AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'messageType': json['messageType'] == null ? undefined : json['messageType'],
        'mmsi': json['mmsi'] == null ? undefined : json['mmsi'],
        'msgtime': json['msgtime'] == null ? undefined : (new Date(json['msgtime'])),
        'functionalId': json['functionalId'] == null ? undefined : json['functionalId'],
        'designatedAreaCode': json['designatedAreaCode'] == null ? undefined : json['designatedAreaCode'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'day': json['day'] == null ? undefined : json['day'],
        'hour': json['hour'] == null ? undefined : json['hour'],
        'minute': json['minute'] == null ? undefined : json['minute'],
        'avgWindSpeed': json['avgWindSpeed'] == null ? undefined : json['avgWindSpeed'],
        'windGust': json['windGust'] == null ? undefined : json['windGust'],
        'windDirection': json['windDirection'] == null ? undefined : json['windDirection'],
        'windGustDirection': json['windGustDirection'] == null ? undefined : json['windGustDirection'],
        'airTemperature': json['airTemperature'] == null ? undefined : json['airTemperature'],
        'relativeHumidity': json['relativeHumidity'] == null ? undefined : json['relativeHumidity'],
        'dewPoint': json['dewPoint'] == null ? undefined : json['dewPoint'],
        'airPressure': json['airPressure'] == null ? undefined : json['airPressure'],
        'airPressureTendency': json['airPressureTendency'] == null ? undefined : AisSharedMessagesEnumsMetHydTrendFromJSON(json['airPressureTendency']),
        'horizontalVisibility': json['horizontalVisibility'] == null ? undefined : json['horizontalVisibility'],
        'waterLevel': json['waterLevel'] == null ? undefined : json['waterLevel'],
        'waterLevelTrend': json['waterLevelTrend'] == null ? undefined : AisSharedMessagesEnumsMetHydTrendFromJSON(json['waterLevelTrend']),
        'surfaceCurrentSpeed': json['surfaceCurrentSpeed'] == null ? undefined : json['surfaceCurrentSpeed'],
        'surfaceCurrentDirection': json['surfaceCurrentDirection'] == null ? undefined : json['surfaceCurrentDirection'],
        'currentSpeed2': json['currentSpeed2'] == null ? undefined : json['currentSpeed2'],
        'currentDirection2': json['currentDirection2'] == null ? undefined : json['currentDirection2'],
        'currentMeasuringLevel2': json['currentMeasuringLevel2'] == null ? undefined : json['currentMeasuringLevel2'],
        'currentSpeed3': json['currentSpeed3'] == null ? undefined : json['currentSpeed3'],
        'currentDirection3': json['currentDirection3'] == null ? undefined : json['currentDirection3'],
        'currentMeasuringLevel3': json['currentMeasuringLevel3'] == null ? undefined : json['currentMeasuringLevel3'],
        'significantWaveHeight': json['significantWaveHeight'] == null ? undefined : json['significantWaveHeight'],
        'wavePeriod': json['wavePeriod'] == null ? undefined : json['wavePeriod'],
        'waveDirection': json['waveDirection'] == null ? undefined : json['waveDirection'],
        'swellHeight': json['swellHeight'] == null ? undefined : json['swellHeight'],
        'swellPeriod': json['swellPeriod'] == null ? undefined : json['swellPeriod'],
        'swellDirection': json['swellDirection'] == null ? undefined : json['swellDirection'],
        'seaState': json['seaState'] == null ? undefined : AisSharedMessagesEnumsMetHydBeaufortScaleFromJSON(json['seaState']),
        'waterTemperature': json['waterTemperature'] == null ? undefined : json['waterTemperature'],
        'precipitationType': json['precipitationType'] == null ? undefined : AisSharedMessagesEnumsMetHydPrecipitationFromJSON(json['precipitationType']),
        'salinity': json['salinity'] == null ? undefined : json['salinity'],
        'ice': json['ice'] == null ? undefined : AisSharedMessagesEnumsMetHydIceFromJSON(json['ice']),
        'stream': json['stream'] == null ? undefined : json['stream'],
    };
}

export function AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHydToJSON(json: any): AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd {
    return AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHydToJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHydToJSONTyped(value?: Omit<AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd, 'type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageType': value['messageType'],
        'mmsi': value['mmsi'],
        'msgtime': value['msgtime'] == null ? value['msgtime'] : value['msgtime'].toISOString(),
        'functionalId': value['functionalId'],
        'designatedAreaCode': value['designatedAreaCode'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'day': value['day'],
        'hour': value['hour'],
        'minute': value['minute'],
        'avgWindSpeed': value['avgWindSpeed'],
        'windGust': value['windGust'],
        'windDirection': value['windDirection'],
        'windGustDirection': value['windGustDirection'],
        'airTemperature': value['airTemperature'],
        'relativeHumidity': value['relativeHumidity'],
        'dewPoint': value['dewPoint'],
        'airPressure': value['airPressure'],
        'airPressureTendency': AisSharedMessagesEnumsMetHydTrendToJSON(value['airPressureTendency']),
        'horizontalVisibility': value['horizontalVisibility'],
        'waterLevel': value['waterLevel'],
        'waterLevelTrend': AisSharedMessagesEnumsMetHydTrendToJSON(value['waterLevelTrend']),
        'surfaceCurrentSpeed': value['surfaceCurrentSpeed'],
        'surfaceCurrentDirection': value['surfaceCurrentDirection'],
        'currentSpeed2': value['currentSpeed2'],
        'currentDirection2': value['currentDirection2'],
        'currentMeasuringLevel2': value['currentMeasuringLevel2'],
        'currentSpeed3': value['currentSpeed3'],
        'currentDirection3': value['currentDirection3'],
        'currentMeasuringLevel3': value['currentMeasuringLevel3'],
        'significantWaveHeight': value['significantWaveHeight'],
        'wavePeriod': value['wavePeriod'],
        'waveDirection': value['waveDirection'],
        'swellHeight': value['swellHeight'],
        'swellPeriod': value['swellPeriod'],
        'swellDirection': value['swellDirection'],
        'seaState': AisSharedMessagesEnumsMetHydBeaufortScaleToJSON(value['seaState']),
        'waterTemperature': value['waterTemperature'],
        'precipitationType': AisSharedMessagesEnumsMetHydPrecipitationToJSON(value['precipitationType']),
        'salinity': value['salinity'],
        'ice': AisSharedMessagesEnumsMetHydIceToJSON(value['ice']),
        'stream': value['stream'],
    };
}

