/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AisSharedMessagesOutputMessagesOutputPositionMessage
 */
export interface AisSharedMessagesOutputMessagesOutputPositionMessage {
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    readonly type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    messageType?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    courseOverGround?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    aisClass?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    altitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    longitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    navigationalStatus?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    rateOfTurn?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    speedOverGround?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    trueHeading?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    mmsi?: number;
    /**
     * 
     * @type {Date}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    msgtime?: Date;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputPositionMessage
     */
    stream?: string | null;
}

/**
 * Check if a given object implements the AisSharedMessagesOutputMessagesOutputPositionMessage interface.
 */
export function instanceOfAisSharedMessagesOutputMessagesOutputPositionMessage(value: object): value is AisSharedMessagesOutputMessagesOutputPositionMessage {
    return true;
}

export function AisSharedMessagesOutputMessagesOutputPositionMessageFromJSON(json: any): AisSharedMessagesOutputMessagesOutputPositionMessage {
    return AisSharedMessagesOutputMessagesOutputPositionMessageFromJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesOutputPositionMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AisSharedMessagesOutputMessagesOutputPositionMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'messageType': json['messageType'] == null ? undefined : json['messageType'],
        'courseOverGround': json['courseOverGround'] == null ? undefined : json['courseOverGround'],
        'aisClass': json['aisClass'] == null ? undefined : json['aisClass'],
        'altitude': json['altitude'] == null ? undefined : json['altitude'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'navigationalStatus': json['navigationalStatus'] == null ? undefined : json['navigationalStatus'],
        'rateOfTurn': json['rateOfTurn'] == null ? undefined : json['rateOfTurn'],
        'speedOverGround': json['speedOverGround'] == null ? undefined : json['speedOverGround'],
        'trueHeading': json['trueHeading'] == null ? undefined : json['trueHeading'],
        'mmsi': json['mmsi'] == null ? undefined : json['mmsi'],
        'msgtime': json['msgtime'] == null ? undefined : (new Date(json['msgtime'])),
        'stream': json['stream'] == null ? undefined : json['stream'],
    };
}

export function AisSharedMessagesOutputMessagesOutputPositionMessageToJSON(json: any): AisSharedMessagesOutputMessagesOutputPositionMessage {
    return AisSharedMessagesOutputMessagesOutputPositionMessageToJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesOutputPositionMessageToJSONTyped(value?: Omit<AisSharedMessagesOutputMessagesOutputPositionMessage, 'type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageType': value['messageType'],
        'courseOverGround': value['courseOverGround'],
        'aisClass': value['aisClass'],
        'altitude': value['altitude'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'navigationalStatus': value['navigationalStatus'],
        'rateOfTurn': value['rateOfTurn'],
        'speedOverGround': value['speedOverGround'],
        'trueHeading': value['trueHeading'],
        'mmsi': value['mmsi'],
        'msgtime': value['msgtime'] == null ? value['msgtime'] : value['msgtime'].toISOString(),
        'stream': value['stream'],
    };
}

