/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AisSharedMessagesOutputMessagesOutputStaticDataMessage
 */
export interface AisSharedMessagesOutputMessagesOutputStaticDataMessage {
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    readonly type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    messageType?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    mmsi?: number;
    /**
     * 
     * @type {Date}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    msgtime?: Date;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    imoNumber?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    callSign?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    destination?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    eta?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    name?: string | null;
    /**
     * Measured in 1/10 meter, so 14 means 1.4 meters. 255 = draught 25.5 m or greater.
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    draught?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    shipLength?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    shipWidth?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    shipType?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    dimensionA?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    dimensionB?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    dimensionC?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    dimensionD?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    positionFixingDeviceType?: number;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    reportClass?: string;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputStaticDataMessage
     */
    stream?: string | null;
}

/**
 * Check if a given object implements the AisSharedMessagesOutputMessagesOutputStaticDataMessage interface.
 */
export function instanceOfAisSharedMessagesOutputMessagesOutputStaticDataMessage(value: object): value is AisSharedMessagesOutputMessagesOutputStaticDataMessage {
    return true;
}

export function AisSharedMessagesOutputMessagesOutputStaticDataMessageFromJSON(json: any): AisSharedMessagesOutputMessagesOutputStaticDataMessage {
    return AisSharedMessagesOutputMessagesOutputStaticDataMessageFromJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesOutputStaticDataMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AisSharedMessagesOutputMessagesOutputStaticDataMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'messageType': json['messageType'] == null ? undefined : json['messageType'],
        'mmsi': json['mmsi'] == null ? undefined : json['mmsi'],
        'msgtime': json['msgtime'] == null ? undefined : (new Date(json['msgtime'])),
        'imoNumber': json['imoNumber'] == null ? undefined : json['imoNumber'],
        'callSign': json['callSign'] == null ? undefined : json['callSign'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'eta': json['eta'] == null ? undefined : json['eta'],
        'name': json['name'] == null ? undefined : json['name'],
        'draught': json['draught'] == null ? undefined : json['draught'],
        'shipLength': json['shipLength'] == null ? undefined : json['shipLength'],
        'shipWidth': json['shipWidth'] == null ? undefined : json['shipWidth'],
        'shipType': json['shipType'] == null ? undefined : json['shipType'],
        'dimensionA': json['dimensionA'] == null ? undefined : json['dimensionA'],
        'dimensionB': json['dimensionB'] == null ? undefined : json['dimensionB'],
        'dimensionC': json['dimensionC'] == null ? undefined : json['dimensionC'],
        'dimensionD': json['dimensionD'] == null ? undefined : json['dimensionD'],
        'positionFixingDeviceType': json['positionFixingDeviceType'] == null ? undefined : json['positionFixingDeviceType'],
        'reportClass': json['reportClass'] == null ? undefined : json['reportClass'],
        'stream': json['stream'] == null ? undefined : json['stream'],
    };
}

export function AisSharedMessagesOutputMessagesOutputStaticDataMessageToJSON(json: any): AisSharedMessagesOutputMessagesOutputStaticDataMessage {
    return AisSharedMessagesOutputMessagesOutputStaticDataMessageToJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesOutputStaticDataMessageToJSONTyped(value?: Omit<AisSharedMessagesOutputMessagesOutputStaticDataMessage, 'type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageType': value['messageType'],
        'mmsi': value['mmsi'],
        'msgtime': value['msgtime'] == null ? value['msgtime'] : value['msgtime'].toISOString(),
        'imoNumber': value['imoNumber'],
        'callSign': value['callSign'],
        'destination': value['destination'],
        'eta': value['eta'],
        'name': value['name'],
        'draught': value['draught'],
        'shipLength': value['shipLength'],
        'shipWidth': value['shipWidth'],
        'shipType': value['shipType'],
        'dimensionA': value['dimensionA'],
        'dimensionB': value['dimensionB'],
        'dimensionC': value['dimensionC'],
        'dimensionD': value['dimensionD'],
        'positionFixingDeviceType': value['positionFixingDeviceType'],
        'reportClass': value['reportClass'],
        'stream': value['stream'],
    };
}

