/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AisSharedMessagesOutputMessagesAisComboFull
 */
export interface AisSharedMessagesOutputMessagesAisComboFull {
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    mmsi?: number;
    /**
     * 
     * @type {Date}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    msgtime?: Date;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    altitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    courseOverGround?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    longitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    navigationalStatus?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    rateOfTurn?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    speedOverGround?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    trueHeading?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    imoNumber?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    callSign?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    destination?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    eta?: string | null;
    /**
     * Measured in 1/10 meter, so 14 means 1.4 meters. 255 = draught 25.5 m or greater.
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    draught?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    shipLength?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    shipWidth?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    shipType?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    dimensionA?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    dimensionB?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    dimensionC?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    dimensionD?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    positionFixingDeviceType?: number;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    reportClass?: string;
    /**
     * 
     * @type {Date}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    msgtimeStatic?: Date;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesAisComboFull
     */
    stream?: string | null;
}

/**
 * Check if a given object implements the AisSharedMessagesOutputMessagesAisComboFull interface.
 */
export function instanceOfAisSharedMessagesOutputMessagesAisComboFull(value: object): value is AisSharedMessagesOutputMessagesAisComboFull {
    return true;
}

export function AisSharedMessagesOutputMessagesAisComboFullFromJSON(json: any): AisSharedMessagesOutputMessagesAisComboFull {
    return AisSharedMessagesOutputMessagesAisComboFullFromJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesAisComboFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): AisSharedMessagesOutputMessagesAisComboFull {
    if (json == null) {
        return json;
    }
    return {
        
        'mmsi': json['mmsi'] == null ? undefined : json['mmsi'],
        'msgtime': json['msgtime'] == null ? undefined : (new Date(json['msgtime'])),
        'altitude': json['altitude'] == null ? undefined : json['altitude'],
        'courseOverGround': json['courseOverGround'] == null ? undefined : json['courseOverGround'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'navigationalStatus': json['navigationalStatus'] == null ? undefined : json['navigationalStatus'],
        'rateOfTurn': json['rateOfTurn'] == null ? undefined : json['rateOfTurn'],
        'speedOverGround': json['speedOverGround'] == null ? undefined : json['speedOverGround'],
        'trueHeading': json['trueHeading'] == null ? undefined : json['trueHeading'],
        'imoNumber': json['imoNumber'] == null ? undefined : json['imoNumber'],
        'callSign': json['callSign'] == null ? undefined : json['callSign'],
        'name': json['name'] == null ? undefined : json['name'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'eta': json['eta'] == null ? undefined : json['eta'],
        'draught': json['draught'] == null ? undefined : json['draught'],
        'shipLength': json['shipLength'] == null ? undefined : json['shipLength'],
        'shipWidth': json['shipWidth'] == null ? undefined : json['shipWidth'],
        'shipType': json['shipType'] == null ? undefined : json['shipType'],
        'dimensionA': json['dimensionA'] == null ? undefined : json['dimensionA'],
        'dimensionB': json['dimensionB'] == null ? undefined : json['dimensionB'],
        'dimensionC': json['dimensionC'] == null ? undefined : json['dimensionC'],
        'dimensionD': json['dimensionD'] == null ? undefined : json['dimensionD'],
        'positionFixingDeviceType': json['positionFixingDeviceType'] == null ? undefined : json['positionFixingDeviceType'],
        'reportClass': json['reportClass'] == null ? undefined : json['reportClass'],
        'msgtimeStatic': json['msgtimeStatic'] == null ? undefined : (new Date(json['msgtimeStatic'])),
        'stream': json['stream'] == null ? undefined : json['stream'],
    };
}

export function AisSharedMessagesOutputMessagesAisComboFullToJSON(json: any): AisSharedMessagesOutputMessagesAisComboFull {
    return AisSharedMessagesOutputMessagesAisComboFullToJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesAisComboFullToJSONTyped(value?: AisSharedMessagesOutputMessagesAisComboFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mmsi': value['mmsi'],
        'msgtime': value['msgtime'] == null ? value['msgtime'] : value['msgtime'].toISOString(),
        'altitude': value['altitude'],
        'courseOverGround': value['courseOverGround'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'navigationalStatus': value['navigationalStatus'],
        'rateOfTurn': value['rateOfTurn'],
        'speedOverGround': value['speedOverGround'],
        'trueHeading': value['trueHeading'],
        'imoNumber': value['imoNumber'],
        'callSign': value['callSign'],
        'name': value['name'],
        'destination': value['destination'],
        'eta': value['eta'],
        'draught': value['draught'],
        'shipLength': value['shipLength'],
        'shipWidth': value['shipWidth'],
        'shipType': value['shipType'],
        'dimensionA': value['dimensionA'],
        'dimensionB': value['dimensionB'],
        'dimensionC': value['dimensionC'],
        'dimensionD': value['dimensionD'],
        'positionFixingDeviceType': value['positionFixingDeviceType'],
        'reportClass': value['reportClass'],
        'msgtimeStatic': value['msgtimeStatic'] == null ? value['msgtimeStatic'] : value['msgtimeStatic'].toISOString(),
        'stream': value['stream'],
    };
}

