/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AisSharedMessagesOutputMessagesOutputAtonMessage
 */
export interface AisSharedMessagesOutputMessagesOutputAtonMessage {
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    readonly type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    messageType?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    mmsi?: number;
    /**
     * 
     * @type {Date}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    msgtime?: Date;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    dimensionA?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    dimensionB?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    dimensionC?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    dimensionD?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    typeOfAidsToNavigation?: number;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    longitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    typeOfElectronicFixingDevice?: number;
    /**
     * 
     * @type {string}
     * @memberof AisSharedMessagesOutputMessagesOutputAtonMessage
     */
    stream?: string | null;
}

/**
 * Check if a given object implements the AisSharedMessagesOutputMessagesOutputAtonMessage interface.
 */
export function instanceOfAisSharedMessagesOutputMessagesOutputAtonMessage(value: object): value is AisSharedMessagesOutputMessagesOutputAtonMessage {
    return true;
}

export function AisSharedMessagesOutputMessagesOutputAtonMessageFromJSON(json: any): AisSharedMessagesOutputMessagesOutputAtonMessage {
    return AisSharedMessagesOutputMessagesOutputAtonMessageFromJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesOutputAtonMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AisSharedMessagesOutputMessagesOutputAtonMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'messageType': json['messageType'] == null ? undefined : json['messageType'],
        'mmsi': json['mmsi'] == null ? undefined : json['mmsi'],
        'msgtime': json['msgtime'] == null ? undefined : (new Date(json['msgtime'])),
        'dimensionA': json['dimensionA'] == null ? undefined : json['dimensionA'],
        'dimensionB': json['dimensionB'] == null ? undefined : json['dimensionB'],
        'dimensionC': json['dimensionC'] == null ? undefined : json['dimensionC'],
        'dimensionD': json['dimensionD'] == null ? undefined : json['dimensionD'],
        'typeOfAidsToNavigation': json['typeOfAidsToNavigation'] == null ? undefined : json['typeOfAidsToNavigation'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'name': json['name'] == null ? undefined : json['name'],
        'typeOfElectronicFixingDevice': json['typeOfElectronicFixingDevice'] == null ? undefined : json['typeOfElectronicFixingDevice'],
        'stream': json['stream'] == null ? undefined : json['stream'],
    };
}

export function AisSharedMessagesOutputMessagesOutputAtonMessageToJSON(json: any): AisSharedMessagesOutputMessagesOutputAtonMessage {
    return AisSharedMessagesOutputMessagesOutputAtonMessageToJSONTyped(json, false);
}

export function AisSharedMessagesOutputMessagesOutputAtonMessageToJSONTyped(value?: Omit<AisSharedMessagesOutputMessagesOutputAtonMessage, 'type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageType': value['messageType'],
        'mmsi': value['mmsi'],
        'msgtime': value['msgtime'] == null ? value['msgtime'] : value['msgtime'].toISOString(),
        'dimensionA': value['dimensionA'],
        'dimensionB': value['dimensionB'],
        'dimensionC': value['dimensionC'],
        'dimensionD': value['dimensionD'],
        'typeOfAidsToNavigation': value['typeOfAidsToNavigation'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'name': value['name'],
        'typeOfElectronicFixingDevice': value['typeOfElectronicFixingDevice'],
        'stream': value['stream'],
    };
}

