/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoJsonAISFeature } from './GeoJsonAISFeature';
import {
    GeoJsonAISFeatureFromJSON,
    GeoJsonAISFeatureFromJSONTyped,
    GeoJsonAISFeatureToJSON,
    GeoJsonAISFeatureToJSONTyped,
} from './GeoJsonAISFeature';

/**
 * 
 * @export
 * @interface GeoJsonAISFeatureCollection
 */
export interface GeoJsonAISFeatureCollection {
    /**
     * 
     * @type {GeoJsonAISFeatureCollectionTypeEnum}
     * @memberof GeoJsonAISFeatureCollection
     */
    type: GeoJsonAISFeatureCollectionTypeEnum;
    /**
     * 
     * @type {Array<GeoJsonAISFeature>}
     * @memberof GeoJsonAISFeatureCollection
     */
    features: Array<GeoJsonAISFeature>;
    /**
     * 
     * @type {object}
     * @memberof GeoJsonAISFeatureCollection
     */
    bbox?: object | null;
}


/**
 * @export
 */
export const GeoJsonAISFeatureCollectionTypeEnum = {
    FeatureCollection: 'FeatureCollection'
} as const;
export type GeoJsonAISFeatureCollectionTypeEnum = typeof GeoJsonAISFeatureCollectionTypeEnum[keyof typeof GeoJsonAISFeatureCollectionTypeEnum];


/**
 * Check if a given object implements the GeoJsonAISFeatureCollection interface.
 */
export function instanceOfGeoJsonAISFeatureCollection(value: object): value is GeoJsonAISFeatureCollection {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('features' in value) || value['features'] === undefined) return false;
    return true;
}

export function GeoJsonAISFeatureCollectionFromJSON(json: any): GeoJsonAISFeatureCollection {
    return GeoJsonAISFeatureCollectionFromJSONTyped(json, false);
}

export function GeoJsonAISFeatureCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoJsonAISFeatureCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'features': ((json['features'] as Array<any>).map(GeoJsonAISFeatureFromJSON)),
        'bbox': json['bbox'] == null ? undefined : json['bbox'],
    };
}

export function GeoJsonAISFeatureCollectionToJSON(json: any): GeoJsonAISFeatureCollection {
    return GeoJsonAISFeatureCollectionToJSONTyped(json, false);
}

export function GeoJsonAISFeatureCollectionToJSONTyped(value?: GeoJsonAISFeatureCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': ((value['features'] as Array<any>).map(GeoJsonAISFeatureToJSON)),
        'bbox': value['bbox'],
    };
}

