/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AisSharedMessagesOutputMessagesAisComboFull } from './AisSharedMessagesOutputMessagesAisComboFull';
import {
    instanceOfAisSharedMessagesOutputMessagesAisComboFull,
    AisSharedMessagesOutputMessagesAisComboFullFromJSON,
    AisSharedMessagesOutputMessagesAisComboFullFromJSONTyped,
    AisSharedMessagesOutputMessagesAisComboFullToJSON,
} from './AisSharedMessagesOutputMessagesAisComboFull';
import type { AisSharedMessagesOutputMessagesAisComboSimple } from './AisSharedMessagesOutputMessagesAisComboSimple';
import {
    instanceOfAisSharedMessagesOutputMessagesAisComboSimple,
    AisSharedMessagesOutputMessagesAisComboSimpleFromJSON,
    AisSharedMessagesOutputMessagesAisComboSimpleFromJSONTyped,
    AisSharedMessagesOutputMessagesAisComboSimpleToJSON,
} from './AisSharedMessagesOutputMessagesAisComboSimple';
import type { GeoJsonAISFeature } from './GeoJsonAISFeature';
import {
    instanceOfGeoJsonAISFeature,
    GeoJsonAISFeatureFromJSON,
    GeoJsonAISFeatureFromJSONTyped,
    GeoJsonAISFeatureToJSON,
} from './GeoJsonAISFeature';

/**
 * @type V1CombinedGet200Response
 * Output format is decided by modelFormat and modelType
 * @export
 */
export type V1CombinedGet200Response = Array<AisSharedMessagesOutputMessagesAisComboFull> | Array<AisSharedMessagesOutputMessagesAisComboSimple> | Array<GeoJsonAISFeature>;

export function V1CombinedGet200ResponseFromJSON(json: any): V1CombinedGet200Response {
    return V1CombinedGet200ResponseFromJSONTyped(json, false);
}

export function V1CombinedGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CombinedGet200Response {
    if (json == null) {
        return json;
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'object')) {
            if (json.every(item => instanceOfAisSharedMessagesOutputMessagesAisComboFull(item))) {
                return json.map(value => AisSharedMessagesOutputMessagesAisComboFullFromJSONTyped(value, true));
            }
            if (json.every(item => instanceOfAisSharedMessagesOutputMessagesAisComboSimple(item))) {
                return json.map(value => AisSharedMessagesOutputMessagesAisComboSimpleFromJSONTyped(value, true));
            }
            if (json.every(item => instanceOfGeoJsonAISFeature(item))) {
                return json.map(value => GeoJsonAISFeatureFromJSONTyped(value, true));
            }
        }
        return json;
    }
    return {} as any;
}

export function V1CombinedGet200ResponseToJSON(json: any): any {
    return V1CombinedGet200ResponseToJSONTyped(json, false);
}

export function V1CombinedGet200ResponseToJSONTyped(value?: V1CombinedGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'object')) {
            if (value.every(item => instanceOfAisSharedMessagesOutputMessagesAisComboFull(item))) {
                return value.map(value => AisSharedMessagesOutputMessagesAisComboFullToJSON(value as AisSharedMessagesOutputMessagesAisComboFull));
            }
            if (value.every(item => instanceOfAisSharedMessagesOutputMessagesAisComboSimple(item))) {
                return value.map(value => AisSharedMessagesOutputMessagesAisComboSimpleToJSON(value as AisSharedMessagesOutputMessagesAisComboSimple));
            }
            if (value.every(item => instanceOfGeoJsonAISFeature(item))) {
                return value.map(value => GeoJsonAISFeatureToJSON(value as GeoJsonAISFeature));
            }
        }
        return value;
    }
    return {};
}

