/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AisSharedMessagesOutputMessagesOutputAtonMessage } from './AisSharedMessagesOutputMessagesOutputAtonMessage';
import {
    instanceOfAisSharedMessagesOutputMessagesOutputAtonMessage,
    AisSharedMessagesOutputMessagesOutputAtonMessageFromJSON,
    AisSharedMessagesOutputMessagesOutputAtonMessageFromJSONTyped,
    AisSharedMessagesOutputMessagesOutputAtonMessageToJSON,
} from './AisSharedMessagesOutputMessagesOutputAtonMessage';
import type { AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd } from './AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd';
import {
    instanceOfAisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd,
    AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHydFromJSON,
    AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHydFromJSONTyped,
    AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHydToJSON,
} from './AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd';
import type { AisSharedMessagesOutputMessagesOutputPositionMessage } from './AisSharedMessagesOutputMessagesOutputPositionMessage';
import {
    instanceOfAisSharedMessagesOutputMessagesOutputPositionMessage,
    AisSharedMessagesOutputMessagesOutputPositionMessageFromJSON,
    AisSharedMessagesOutputMessagesOutputPositionMessageFromJSONTyped,
    AisSharedMessagesOutputMessagesOutputPositionMessageToJSON,
} from './AisSharedMessagesOutputMessagesOutputPositionMessage';
import type { AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage } from './AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage';
import {
    instanceOfAisSharedMessagesOutputMessagesOutputSafetyRelatedMessage,
    AisSharedMessagesOutputMessagesOutputSafetyRelatedMessageFromJSON,
    AisSharedMessagesOutputMessagesOutputSafetyRelatedMessageFromJSONTyped,
    AisSharedMessagesOutputMessagesOutputSafetyRelatedMessageToJSON,
} from './AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage';
import type { AisSharedMessagesOutputMessagesOutputStaticDataMessage } from './AisSharedMessagesOutputMessagesOutputStaticDataMessage';
import {
    instanceOfAisSharedMessagesOutputMessagesOutputStaticDataMessage,
    AisSharedMessagesOutputMessagesOutputStaticDataMessageFromJSON,
    AisSharedMessagesOutputMessagesOutputStaticDataMessageFromJSONTyped,
    AisSharedMessagesOutputMessagesOutputStaticDataMessageToJSON,
} from './AisSharedMessagesOutputMessagesOutputStaticDataMessage';

/**
 * @type V1LatestAisGet200ResponseInner
 * 
 * @export
 */
export type V1LatestAisGet200ResponseInner = AisSharedMessagesOutputMessagesOutputAtonMessage | AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd | AisSharedMessagesOutputMessagesOutputPositionMessage | AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage | AisSharedMessagesOutputMessagesOutputStaticDataMessage;

export function V1LatestAisGet200ResponseInnerFromJSON(json: any): V1LatestAisGet200ResponseInner {
    return V1LatestAisGet200ResponseInnerFromJSONTyped(json, false);
}

export function V1LatestAisGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1LatestAisGet200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAisSharedMessagesOutputMessagesOutputAtonMessage(json)) {
        return AisSharedMessagesOutputMessagesOutputAtonMessageFromJSONTyped(json, true);
    }
    if (instanceOfAisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd(json)) {
        return AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHydFromJSONTyped(json, true);
    }
    if (instanceOfAisSharedMessagesOutputMessagesOutputPositionMessage(json)) {
        return AisSharedMessagesOutputMessagesOutputPositionMessageFromJSONTyped(json, true);
    }
    if (instanceOfAisSharedMessagesOutputMessagesOutputSafetyRelatedMessage(json)) {
        return AisSharedMessagesOutputMessagesOutputSafetyRelatedMessageFromJSONTyped(json, true);
    }
    if (instanceOfAisSharedMessagesOutputMessagesOutputStaticDataMessage(json)) {
        return AisSharedMessagesOutputMessagesOutputStaticDataMessageFromJSONTyped(json, true);
    }
    return {} as any;
}

export function V1LatestAisGet200ResponseInnerToJSON(json: any): any {
    return V1LatestAisGet200ResponseInnerToJSONTyped(json, false);
}

export function V1LatestAisGet200ResponseInnerToJSONTyped(value?: V1LatestAisGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAisSharedMessagesOutputMessagesOutputAtonMessage(value)) {
        return AisSharedMessagesOutputMessagesOutputAtonMessageToJSON(value as AisSharedMessagesOutputMessagesOutputAtonMessage);
    }
    if (instanceOfAisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd(value)) {
        return AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHydToJSON(value as AisSharedMessagesOutputMessagesOutputBinaryBroadcastMessageMetHyd);
    }
    if (instanceOfAisSharedMessagesOutputMessagesOutputPositionMessage(value)) {
        return AisSharedMessagesOutputMessagesOutputPositionMessageToJSON(value as AisSharedMessagesOutputMessagesOutputPositionMessage);
    }
    if (instanceOfAisSharedMessagesOutputMessagesOutputSafetyRelatedMessage(value)) {
        return AisSharedMessagesOutputMessagesOutputSafetyRelatedMessageToJSON(value as AisSharedMessagesOutputMessagesOutputSafetyRelatedMessage);
    }
    if (instanceOfAisSharedMessagesOutputMessagesOutputStaticDataMessage(value)) {
        return AisSharedMessagesOutputMessagesOutputStaticDataMessageToJSON(value as AisSharedMessagesOutputMessagesOutputStaticDataMessage);
    }
    return {};
}

