/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AisLiveApiApiLatestAisModelsLatestAisCombinedFilterInput,
  AisLiveApiApiLatestAisModelsLatestAisFilterInput,
  AisLiveApiApiLatestAisModelsModelFormat,
  AisSharedModelsEnumsModelType,
  MicrosoftAspNetCoreMvcProblemDetails,
  V1LatestAisGet200ResponseInner,
  V1LatestCombinedGet200Response,
} from '../models/index';
import {
    AisLiveApiApiLatestAisModelsLatestAisCombinedFilterInputFromJSON,
    AisLiveApiApiLatestAisModelsLatestAisCombinedFilterInputToJSON,
    AisLiveApiApiLatestAisModelsLatestAisFilterInputFromJSON,
    AisLiveApiApiLatestAisModelsLatestAisFilterInputToJSON,
    AisLiveApiApiLatestAisModelsModelFormatFromJSON,
    AisLiveApiApiLatestAisModelsModelFormatToJSON,
    AisSharedModelsEnumsModelTypeFromJSON,
    AisSharedModelsEnumsModelTypeToJSON,
    MicrosoftAspNetCoreMvcProblemDetailsFromJSON,
    MicrosoftAspNetCoreMvcProblemDetailsToJSON,
    V1LatestAisGet200ResponseInnerFromJSON,
    V1LatestAisGet200ResponseInnerToJSON,
    V1LatestCombinedGet200ResponseFromJSON,
    V1LatestCombinedGet200ResponseToJSON,
} from '../models/index';

export interface V1LatestAisGetRequest {
    since?: Date;
}

export interface V1LatestAisPostRequest {
    aisLiveApiApiLatestAisModelsLatestAisFilterInput?: AisLiveApiApiLatestAisModelsLatestAisFilterInput;
}

export interface V1LatestCombinedGetRequest {
    since?: Date;
    modelType?: AisSharedModelsEnumsModelType;
    modelFormat?: AisLiveApiApiLatestAisModelsModelFormat;
}

export interface V1LatestCombinedPostRequest {
    aisLiveApiApiLatestAisModelsLatestAisCombinedFilterInput?: AisLiveApiApiLatestAisModelsLatestAisCombinedFilterInput;
}

/**
 * 
 */
export class AISLatestApi extends runtime.BaseAPI {

    /**
     * Creates request options for v1LatestAisGet without sending the request
     */
    async v1LatestAisGetRequestOpts(requestParameters: V1LatestAisGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['since'] != null) {
            queryParameters['since'] = (requestParameters['since'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/latest/ais`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the latest AIS messages per MMSI within 24 hours.
     */
    async v1LatestAisGetRaw(requestParameters: V1LatestAisGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<V1LatestAisGet200ResponseInner>>> {
        const requestOptions = await this.v1LatestAisGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(V1LatestAisGet200ResponseInnerFromJSON));
    }

    /**
     * Get the latest AIS messages per MMSI within 24 hours.
     */
    async v1LatestAisGet(requestParameters: V1LatestAisGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<V1LatestAisGet200ResponseInner>> {
        const response = await this.v1LatestAisGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1LatestAisPost without sending the request
     */
    async v1LatestAisPostRequestOpts(requestParameters: V1LatestAisPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/latest/ais`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AisLiveApiApiLatestAisModelsLatestAisFilterInputToJSON(requestParameters['aisLiveApiApiLatestAisModelsLatestAisFilterInput']),
        };
    }

    /**
     * Get the latest AIS messages per MMSI within 24 hours.
     */
    async v1LatestAisPostRaw(requestParameters: V1LatestAisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<V1LatestAisGet200ResponseInner>>> {
        const requestOptions = await this.v1LatestAisPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(V1LatestAisGet200ResponseInnerFromJSON));
    }

    /**
     * Get the latest AIS messages per MMSI within 24 hours.
     */
    async v1LatestAisPost(requestParameters: V1LatestAisPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<V1LatestAisGet200ResponseInner>> {
        const response = await this.v1LatestAisPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1LatestCombinedGet without sending the request
     */
    async v1LatestCombinedGetRequestOpts(requestParameters: V1LatestCombinedGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['since'] != null) {
            queryParameters['since'] = (requestParameters['since'] as any).toISOString();
        }

        if (requestParameters['modelType'] != null) {
            queryParameters['modelType'] = requestParameters['modelType'];
        }

        if (requestParameters['modelFormat'] != null) {
            queryParameters['modelFormat'] = requestParameters['modelFormat'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/latest/combined`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Geojson returns a list with GeoJSON features. FeatureCollection returns a FeatureCollection object.
     * Get the latest AIS messages per MMSI within 24 hours.
     */
    async v1LatestCombinedGetRaw(requestParameters: V1LatestCombinedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1LatestCombinedGet200Response>> {
        const requestOptions = await this.v1LatestCombinedGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LatestCombinedGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Geojson returns a list with GeoJSON features. FeatureCollection returns a FeatureCollection object.
     * Get the latest AIS messages per MMSI within 24 hours.
     */
    async v1LatestCombinedGet(requestParameters: V1LatestCombinedGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1LatestCombinedGet200Response> {
        const response = await this.v1LatestCombinedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1LatestCombinedPost without sending the request
     */
    async v1LatestCombinedPostRequestOpts(requestParameters: V1LatestCombinedPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/latest/combined`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AisLiveApiApiLatestAisModelsLatestAisCombinedFilterInputToJSON(requestParameters['aisLiveApiApiLatestAisModelsLatestAisCombinedFilterInput']),
        };
    }

    /**
     * Geojson returns a list with GeoJSON features. FeatureCollection returns a FeatureCollection object.
     * Get the latest AIS messages per MMSI within 24 hours.
     */
    async v1LatestCombinedPostRaw(requestParameters: V1LatestCombinedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1LatestCombinedGet200Response>> {
        const requestOptions = await this.v1LatestCombinedPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LatestCombinedGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Geojson returns a list with GeoJSON features. FeatureCollection returns a FeatureCollection object.
     * Get the latest AIS messages per MMSI within 24 hours.
     */
    async v1LatestCombinedPost(requestParameters: V1LatestCombinedPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1LatestCombinedGet200Response> {
        const response = await this.v1LatestCombinedPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
