/* tslint:disable */
/* eslint-disable */
/**
 * AIS Live API
 *  API for retrieval of AIS (Automatic Identification System) data. The data is provided by The Norwegian Coastal Administration (Kystverket).  This is a JSON streaming API for a subset of the data available in the AIS data. As long as you are connected you will receive new messages as they arrive.  Some endpoints allow downsampling. When downsampling is enabled maximum one message per minute per mmsi/vessel is sent.  AIS message types in this API: * AIS message type 1, 2, 3, 9, 18, 19, 27: position report, output as type \'Position\' * AIS message type 5, 24: static and voyage related data, output as type \'StaticData\' * AIS message type 8: Binary Broadcast Message with MetHyd data, output as type \'BinaryBroadcastMessageMetHyd\' * AIS message type 21: Aids-to-navigation, output as type \'Aton\'  More message types may be added in the future.  Details about the AIS standard and different message types can be found here: [https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation](https://gpsd.gitlab.io/gpsd/AIVDM.html#_ais_payload_interpretation) .  This API is used by [NAIS](https://nais.kystverket.no), a Norwegian Coastal Administration application for viewing maritime traffic in Norwegian waters.  ### Authentication Before using this API you need to register a user at barentswatch.no and create an AIS-API client at My Page. Instructions and examples can be found here: [https://developer.barentswatch.no/docs/appreg](https://developer.barentswatch.no/docs/appreg)  ### API news General API information and notifications about changes to the API: [https://developer.barentswatch.no](https://developer.barentswatch.no)   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AisLiveApiApiLiveAisModelsLiveAisCombinedFilterInput,
  AisLiveApiApiLiveAisModelsLiveAisFilterInput,
  AisLiveApiApiLiveAisModelsModelFormat,
  AisSharedModelsEnumsModelType,
  MicrosoftAspNetCoreMvcProblemDetails,
  V1CombinedGet200Response,
  V1LatestAisGet200ResponseInner,
} from '../models/index';
import {
    AisLiveApiApiLiveAisModelsLiveAisCombinedFilterInputFromJSON,
    AisLiveApiApiLiveAisModelsLiveAisCombinedFilterInputToJSON,
    AisLiveApiApiLiveAisModelsLiveAisFilterInputFromJSON,
    AisLiveApiApiLiveAisModelsLiveAisFilterInputToJSON,
    AisLiveApiApiLiveAisModelsModelFormatFromJSON,
    AisLiveApiApiLiveAisModelsModelFormatToJSON,
    AisSharedModelsEnumsModelTypeFromJSON,
    AisSharedModelsEnumsModelTypeToJSON,
    MicrosoftAspNetCoreMvcProblemDetailsFromJSON,
    MicrosoftAspNetCoreMvcProblemDetailsToJSON,
    V1CombinedGet200ResponseFromJSON,
    V1CombinedGet200ResponseToJSON,
    V1LatestAisGet200ResponseInnerFromJSON,
    V1LatestAisGet200ResponseInnerToJSON,
} from '../models/index';

export interface V1AisPostRequest {
    aisLiveApiApiLiveAisModelsLiveAisFilterInput?: AisLiveApiApiLiveAisModelsLiveAisFilterInput;
}

export interface V1CombinedGetRequest {
    modelType?: AisSharedModelsEnumsModelType;
    modelFormat?: AisLiveApiApiLiveAisModelsModelFormat;
}

export interface V1CombinedPostRequest {
    aisLiveApiApiLiveAisModelsLiveAisCombinedFilterInput?: AisLiveApiApiLiveAisModelsLiveAisCombinedFilterInput;
}

export interface V1SseAisPostRequest {
    aisLiveApiApiLiveAisModelsLiveAisFilterInput?: AisLiveApiApiLiveAisModelsLiveAisFilterInput;
}

export interface V1SseCombinedGetRequest {
    modelType?: AisSharedModelsEnumsModelType;
    modelFormat?: AisLiveApiApiLiveAisModelsModelFormat;
}

export interface V1SseCombinedPostRequest {
    aisLiveApiApiLiveAisModelsLiveAisCombinedFilterInput?: AisLiveApiApiLiveAisModelsLiveAisCombinedFilterInput;
}

/**
 * 
 */
export class AISStreamApi extends runtime.BaseAPI {

    /**
     * Creates request options for v1AisGet without sending the request
     */
    async v1AisGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/ais`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Messages are separated by line breaks (\\n).              The different message schemas returned can be recognized by looking at the \'type\' field.              This endpoint has no filter capabilities. Use the POST version of this endpoint if you need filtering.
     * AIS stream
     */
    async v1AisGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1LatestAisGet200ResponseInner>> {
        const requestOptions = await this.v1AisGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LatestAisGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Messages are separated by line breaks (\\n).              The different message schemas returned can be recognized by looking at the \'type\' field.              This endpoint has no filter capabilities. Use the POST version of this endpoint if you need filtering.
     * AIS stream
     */
    async v1AisGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1LatestAisGet200ResponseInner> {
        const response = await this.v1AisGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1AisPost without sending the request
     */
    async v1AisPostRequestOpts(requestParameters: V1AisPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/ais`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AisLiveApiApiLiveAisModelsLiveAisFilterInputToJSON(requestParameters['aisLiveApiApiLiveAisModelsLiveAisFilterInput']),
        };
    }

    /**
     * Messages are separated by line breaks (\\n).              You can optionally filter on message type, mmsi and geometry, and also enable downsampling.
     * AIS stream with optional filter
     */
    async v1AisPostRaw(requestParameters: V1AisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1LatestAisGet200ResponseInner>> {
        const requestOptions = await this.v1AisPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LatestAisGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Messages are separated by line breaks (\\n).              You can optionally filter on message type, mmsi and geometry, and also enable downsampling.
     * AIS stream with optional filter
     */
    async v1AisPost(requestParameters: V1AisPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1LatestAisGet200ResponseInner> {
        const response = await this.v1AisPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1CombinedGet without sending the request
     */
    async v1CombinedGetRequestOpts(requestParameters: V1CombinedGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['modelType'] != null) {
            queryParameters['modelType'] = requestParameters['modelType'];
        }

        if (requestParameters['modelFormat'] != null) {
            queryParameters['modelFormat'] = requestParameters['modelFormat'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/combined`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Messages are separated by line breaks (\\n).              This endpoint has no filter capabilities. Use the POST version of this endpoint if you need filtering.
     * AIS stream of combined position and static data for one entity
     */
    async v1CombinedGetRaw(requestParameters: V1CombinedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1CombinedGet200Response>> {
        const requestOptions = await this.v1CombinedGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1CombinedGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Messages are separated by line breaks (\\n).              This endpoint has no filter capabilities. Use the POST version of this endpoint if you need filtering.
     * AIS stream of combined position and static data for one entity
     */
    async v1CombinedGet(requestParameters: V1CombinedGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1CombinedGet200Response> {
        const response = await this.v1CombinedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1CombinedPost without sending the request
     */
    async v1CombinedPostRequestOpts(requestParameters: V1CombinedPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/combined`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AisLiveApiApiLiveAisModelsLiveAisCombinedFilterInputToJSON(requestParameters['aisLiveApiApiLiveAisModelsLiveAisCombinedFilterInput']),
        };
    }

    /**
     * Messages are separated by line breaks (\\n).              You can optionally filter on mmsi and geometry, and also enable downsampling.
     * AIS stream of combined position and static data for one entity, with optional filter
     */
    async v1CombinedPostRaw(requestParameters: V1CombinedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1CombinedGet200Response>> {
        const requestOptions = await this.v1CombinedPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1CombinedGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Messages are separated by line breaks (\\n).              You can optionally filter on mmsi and geometry, and also enable downsampling.
     * AIS stream of combined position and static data for one entity, with optional filter
     */
    async v1CombinedPost(requestParameters: V1CombinedPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1CombinedGet200Response> {
        const response = await this.v1CombinedPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1SseAisGet without sending the request
     */
    async v1SseAisGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sse/ais`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The different message schemas returned can be recognized by looking at the \'type\' field.              This endpoint has no filter capabilities. Use the POST version of this endpoint if you need filtering.
     * AIS stream as SSE (Server Sent Events)
     */
    async v1SseAisGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1LatestAisGet200ResponseInner>> {
        const requestOptions = await this.v1SseAisGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LatestAisGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * The different message schemas returned can be recognized by looking at the \'type\' field.              This endpoint has no filter capabilities. Use the POST version of this endpoint if you need filtering.
     * AIS stream as SSE (Server Sent Events)
     */
    async v1SseAisGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1LatestAisGet200ResponseInner> {
        const response = await this.v1SseAisGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1SseAisPost without sending the request
     */
    async v1SseAisPostRequestOpts(requestParameters: V1SseAisPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/sse/ais`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AisLiveApiApiLiveAisModelsLiveAisFilterInputToJSON(requestParameters['aisLiveApiApiLiveAisModelsLiveAisFilterInput']),
        };
    }

    /**
     * You can optionally filter on message type, mmsi and geometry, and also enable downsampling.
     * AIS stream as SSE (Server Sent Events) with optional filter
     */
    async v1SseAisPostRaw(requestParameters: V1SseAisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1LatestAisGet200ResponseInner>> {
        const requestOptions = await this.v1SseAisPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LatestAisGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * You can optionally filter on message type, mmsi and geometry, and also enable downsampling.
     * AIS stream as SSE (Server Sent Events) with optional filter
     */
    async v1SseAisPost(requestParameters: V1SseAisPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1LatestAisGet200ResponseInner> {
        const response = await this.v1SseAisPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1SseCombinedGet without sending the request
     */
    async v1SseCombinedGetRequestOpts(requestParameters: V1SseCombinedGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['modelType'] != null) {
            queryParameters['modelType'] = requestParameters['modelType'];
        }

        if (requestParameters['modelFormat'] != null) {
            queryParameters['modelFormat'] = requestParameters['modelFormat'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sse/combined`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint has no filter capabilities. Use the POST version of this endpoint if you need filtering.
     * AIS stream of combined position and static data for one entity as SSE (Server Sent Events)
     */
    async v1SseCombinedGetRaw(requestParameters: V1SseCombinedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1CombinedGet200Response>> {
        const requestOptions = await this.v1SseCombinedGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1CombinedGet200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint has no filter capabilities. Use the POST version of this endpoint if you need filtering.
     * AIS stream of combined position and static data for one entity as SSE (Server Sent Events)
     */
    async v1SseCombinedGet(requestParameters: V1SseCombinedGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1CombinedGet200Response> {
        const response = await this.v1SseCombinedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1SseCombinedPost without sending the request
     */
    async v1SseCombinedPostRequestOpts(requestParameters: V1SseCombinedPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/sse/combined`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AisLiveApiApiLiveAisModelsLiveAisCombinedFilterInputToJSON(requestParameters['aisLiveApiApiLiveAisModelsLiveAisCombinedFilterInput']),
        };
    }

    /**
     * You can optionally filter on mmsi and geometry, and also enable downsampling.
     * AIS stream of combined position and static data for one entity as SSE (Server Sent Events), with optional filter
     */
    async v1SseCombinedPostRaw(requestParameters: V1SseCombinedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1CombinedGet200Response>> {
        const requestOptions = await this.v1SseCombinedPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1CombinedGet200ResponseFromJSON(jsonValue));
    }

    /**
     * You can optionally filter on mmsi and geometry, and also enable downsampling.
     * AIS stream of combined position and static data for one entity as SSE (Server Sent Events), with optional filter
     */
    async v1SseCombinedPost(requestParameters: V1SseCombinedPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1CombinedGet200Response> {
        const response = await this.v1SseCombinedPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
